"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys


# import ldap
# from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

# # 1. Connection Settings
# AUTH_LDAP_SERVER_URI = "ldap://your-ad-server.company.com"
# AUTH_LDAP_BIND_DN = "CN=ServiceAccount,OU=ServiceAccounts,DC=company,DC=com"
# AUTH_LDAP_BIND_PASSWORD = "your-password"
# AUTH_LDAP_USER_SEARCH = LDAPSearch("OU=Users,DC=company,DC=com", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")

# 2. RBAC: Group Mapping
# Maps AD Groups to Django user attributes (is_staff/is_superuser)
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "CN=GOC_Operators,OU=Groups,DC=company,DC=com",
    "is_staff": "CN=GOC_Admins,OU=Groups,DC=company,DC=com",
}

# 3. Custom RBAC Mapping for Towers
# You can check these in your views to hide/show towers (Unix, Middleware, etc.)
AUTH_LDAP_FIND_GROUP_PERMS = True

AUTHENTICATION_BACKENDS = [
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'mcp_stderr': {
#             'class': 'logging.StreamHandler',
#             'stream': sys.stderr, # Must be sys.stderr
#         },
#     },
#     'root': {
#         'handlers': ['mcp_stderr'],
#         'level': 'WARNING',
#     },
# }

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-em!dzy^@8=#$j9a98d@z5#+(89i!l63861+qd#dip%2lw)pn3g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.58']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mcp_server',
    'django_extensions',
    'polls',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'polls/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MCP_SERVER_REQUIRE_AUTH = True

DJANGO_MCP_TOOLSETS = [
    'polls.mcp_tools.CalculatorTools',
]